Util: Remove unused lifetime arg from impl Serialize for HashString
This fixes a clippy finding:

error: this lifetime isn't used in the impl
  --> src/util.rs:64:6
   |
64 | impl<'a, T> Serialize for HashString<T>
   |      ^^
   |